Working Copy od Sean code/NurseryS/NurseryS/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NurseryS.Models;
using NurseryS.Context;

namespace NurseryS.Controllers
{
    public class PostController : Controller
    {
        private DataContext db = new DataContext();

        //
        // GET: /Post/

        public ActionResult Index()
        {
            return View(db.Posts.Where(m => m.Account.UserName.Equals(User.Identity.Name)).ToList());
        }

        //
        // GET: /Post/Details/5

        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Post/Create

        [Authorize(Roles="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="Admin")]
        [ValidateInput(false)] 
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                post.Account = db.Accounts.SingleOrDefault(a => a.UserName.Equals(HttpContext.User.Identity.Name));
                int maxId = 0;
                foreach(Post pt in db.Posts.ToArray())
                {
                    if(pt.ID>maxId)
                    {
                        maxId = pt.ID;
                    }
                }
                post.ID = maxId + 1;
                post.CreateDate = DateTime.Now;
                post.ReleaseDate = DateTime.Now;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index", "Home", null);
            }

            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="Admin")]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Working Copy od Sean code/NurseryS/NurseryS/Views/Shared/_BootstrapLayout1.cshtml
@using System.Web.Optimization
@using NurseryS.ViewModels;
@model ViewModelBase
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    
    <!-- TINYMCE Place inside the <head> of your HTML -->
    <script type="text/javascript" src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea",
            toolbar: [
        "undo redo | styleselect | bold italic | link image",
        "alignleft aligncenter alignright"
            ],
            menubar: "tools table format view insert edit"
        });
    </script>
    


    <!-- styles -->
    @Styles.Render("~/Content/bootstrap-theme/css", "~/Content/css")
    
    <link href="~/Content/bootstrap.css" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet">


    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="~/Content/icons/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/icons/apple-touch-icon-57-precomposed.png">
      @if(IsSectionDefined("AddToHead")){
        @RenderSection("AddToHead", false)
      }
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="example.css">
  </head>
    
  <body class="body-bg">
  <div id="wrapper">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
         <div class="container">
             @*
           <div class="nav fixed-right pull-right ">
             <div class="row">
               @Html.Partial("_LoginPartial") 
             </div>
           </div>
             *@
           <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </a>
            
           @Html.Partial("_TopMenuPartial", Model) 

        </div>
      </div>
    </div>
      

    <div id="main">
    <div class="container-fluid" >
      <div class="row-fluid">
           <div>
               <br />
               <br />
               <br />
               <br />
               <br />
               <br />
        @RenderBody()
           </div>
      </div>
    </div> <!-- /container -->
        
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
    </div>
  </div>
  @Html.Partial("_FooterPartial")
      @if(IsSectionDefined("AddToEnd")){
            @RenderSection("AddToEnd", false)
      }

      <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

Working Copy od Sean code/NurseryS/NurseryS/Views/Shared/_FooterPartial.cshtml
<div class="navbar span12">
    <div id="footer" style="background-color: rgba(22,22,22,0)">         
        Date: @DateTime.Now.Month / @DateTime.Now.Day / @DateTime.Now.Year  - Nursery Application
        <br />
        @Html.Raw("&copy;") 2015 North Oaks Hospital
    </div>
</div>
        

Working Copy od Sean code/NurseryS/NurseryS/Views/Shared/_Layout.cshtml
@using NurseryS.Infrastructure
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>SOS - @ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <!--Start of Telerik head-->
@*            @(Html.Telerik().StyleSheetRegistrar().DefaultGroup(group => group.Add("telerik.common.css").Add("telerik.windows7.css").Combined(true).Compress(true)))*@
        <!--End of Telerik head-->
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <img src="~/Images/SOSLogo.png" alt="Student Organization Simplifier" width="146" height="87" />
                </div>
                <div class="site-title">
                    @Html.ActionLink("Nursery", "Index", "Home")
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
@*                    <section id="navmenu">
                        @Html.Partial("_NavMenuPartial")
                    </section>*@
                </div>
            </div>
        </header>

        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                <table>
                    <tr>
@*                        <td >
                <section id="vnavmenu">
                    @Html.Partial("_VNavMenuPartial")
                </section>
                        </td>*@
                        <td>
                @RenderBody()
                        </td>
                    </tr>
                </table>
            </section>
        </div>
        
        } 
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>
                        
                        Date: @DateTime.Now.Month / @DateTime.Now.Day / @DateTime.Now.Year  - SOS Test Version: v1.04

                    </p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)

    </body>
</html>

Working Copy od Sean code/NurseryS/NurseryS/Views/Shared/_LeftMenuMemberPartial.cshtml
@*@{
    <div class="tabbable tabs-left">
        <ul class="nav nav-tabs">
            <li @{if ((ViewContext.RouteData.Values["action"].ToString().Equals("Index"))
                      && (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.HomeController().GetType().Name))){<text>class="active"</text>}}><a class="brand" href="~/Home/Index"> <img src="~/Images/SOSLogo.png" alt="Student Organization Simplifier" width="146" height="87"></a></li>
            @if (User.Identity.Name == "Admin1") {
                  <li @{if ((ViewContext.RouteData.Values["action"].ToString().Equals("Index"))
                      && (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.AdminController().GetType().Name))){<text>class="active"</text>}}><a href="~/Account/Index">Account</a></li>
            }
            @if (User.Identity.Name == "Member1") {
                  <li @{if ((ViewContext.RouteData.Values["action"].ToString().Equals("Index"))
                      && (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.MemberController().GetType().Name))){<text>class="active"</text>}}><a href="~/Account/Index">Account</a></li>
            }
            @if (User.Identity.Name == "Leader1") {
                  <li @{if ((ViewContext.RouteData.Values["action"].ToString().Equals("Index"))
                      && (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.LeaderController().GetType().Name))){<text>class="active"</text>}}><a href="~/Account/Index">Account</a></li>
            }

            <li @{if ((ViewContext.RouteData.Values["action"].ToString().Equals("Index"))
                      && (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.OrganizationController().GetType().Name))){<text>class="active"</text>}}><a href="~/Organization/Index">Organizations</a></li>
            <li @{if((ViewContext.RouteData.Values["action"].ToString().Equals("Calendar"))
                      && (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.OrganizationController().GetType().Name))){<text>class="active"</text>}}><a href="~/Organization/Calendar">Calendar</a></li>

        </ul>
        <div class="tab-content">
        
        </div>
    </div>
}*@
@{
    var Cntrl = ViewContext.RouteData.Values["controller"].ToString();
    var Action = ViewContext.RouteData.Values["action"].ToString();
}


<div class="nav span2 ">
@*                <form action="http://localhost/NurseryS/Home/SearchResults/">
                <div style="float: left;"><input type="text" name="q" id="tipue_search_input"></div>
                <div style="float: left; margin-left: 13px;"><input type="button" id="tipue_search_button" onclick="this.form.submit();"></div>
                </form>
                <div style="clear: both"></div>*@
    @if (User.Identity.IsAuthenticated)
    {
        @Html.Partial("_StandardSideBarPartial");
    }
    @if (Cntrl.Equals("Organization") && Action.Equals("FrontPage"))
    {
        @Html.Partial("_OrganizationToolbarPartial");
    }


</div>
   
    
    

@*{
    
    <div class="container">
        <div class =" span3 bs-docs-sidebar">
            <ul class ="nav nva-list bs-docs-sidenav">
                <li><a href="~/Organization/Index">Organizations</a></li>
                <li><a href="~Organization/Calendar">Calendar</a></li>
            </ul>
        </div>
    </div>
}*@

Working Copy od Sean code/NurseryS/NurseryS/Views/Shared/_TopMenuPartial.cshtml
@using NurseryS.Infrastructure
@using NurseryS.ViewModels
@model ViewModelBase
@{
    var Cntrl = ViewContext.RouteData.Values["controller"].ToString();
    var Action = ViewContext.RouteData.Values["action"].ToString();
}

<script type="text/javascript">

    function setLogoutValue()
    {
        Model.logout = true;
            
    }

</script>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <form class="navbar-form pull-left">
                <a class="navbar-brand" href="~/Home/Index">NurseryS</a>
          <ul class="nav navbar-nav">
              @if(User.Identity.IsAuthenticated)
              {
              <li>
                  @Html.ActionLink("New Post", "Create", "Post")
              </li>
              }

          </ul>
          </form>
            <form class="navbar-form pull-right">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class ="nav navbar-nav">
                        <li>
                            @Html.ActionLink(User.Identity.Name, "Details", "Account")
                        </li>
                        <li>
                            @Html.ActionLink("Log Off", "Logoff", "Account")
                        </li>
                    </ul>
                    
                    
                }
                @if(!User.Identity.IsAuthenticated)
                {

                    @Html.Partial("_LoginPartial", Model)
     
                }
            </form>
            
        </div><!--/.nav-collapse -->
      </div>
    </nav>
<!--

    <div class="row pull-left" style="padding-left: 20px;">
        <ul class="nav">
            <li><a title="All Organizations" class="brand" href="~/Home/Index">Student Organization Simplifier</a></li>
        </ul>
        <div class="nav-collapse ">
            <ul class="nav nav-tabs">
    @*
                @if(true){//User.Identity.IsAuthenticated){
                    <li @{if ( (Cntrl.Equals("User") && (Action.Equals("HomeConsole")) )){<text>class="active"</text>}}><a href="~/User/HomeConsole">Home Console</a></li>
                }
                @if(true){//User.Identity.IsAuthenticated){
                <li @{if (Cntrl.Equals("Home")){<text>class="active dropdown"</text>} else{<text>class="dropdown"</text>}}>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Organizations <img src="~/Images/1351784046_arrow_state_grey_expanded.png" alt="" /></a>
                    <ul class="dropdown-menu">
    *@
    -->
                        <!-- links -->
<!--
                        <li><a href="~/Home/Index" >Complete Listing</a></li>
                        <li><a href="~/Organization/MyOrganizations" >My Organizations</a></li>
                        <li><a href="~/Organization/CreateNewOrgApplication">New Organization Application</a></li>
                    </ul>
                </li>
                }

               
                if(true){//User.Identity.IsAuthenticated && StaticMethods.getCurrentUserView().isUniversityPresident == true)
                
                 <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Faculty <img src="~/Images/1351784046_arrow_state_grey_expanded.png" alt="" /></a>
                    <ul class="dropdown-menu">

    -->
                        <!-- links -->
                        
                       
                       
                        <!--
                        
                        <li>Html.ActionLink("Manage Org Apps", "ManageNewOrgApps", "Organization", null, null)</li>
                    </ul>
                </li>
                }


                if(true){//User.Identity.IsAuthenticated && User.IsInRole("Administrator")){
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin <img src="~/Images/1351784046_arrow_state_grey_expanded.png" alt="" /></a>
                    <ul class="dropdown-menu">
                            -->
                        <!-- links -->
                        
                       
                       <!--
                        
                        <li><a href="~/User/Index">User Index</a></li>
                        
                    </ul>
                </li>
                }
            </ul>                
                           
        </div>
                           -->
                           <!--/.nav-collapse -->
    <!--  </div>  -->

@*}*@
    @*
    
    
    
<div class="row">
<div class="nav-collapse">
            <ul class="nav">
              <li @{if (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.HomeController().GetType().Name)){<text>class="active"</text>}}> @new {linktext = "home", actionname="index", controllername="home", roles="all, anonymous"}</li> 
              <li @{if (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.MemberController().GetType().Name)){<text>class="active"</text>}   }>@new {linktext = "member", actionname="index", controllername="member", roles="administrator, leader, member"}</li>
              <li @{if (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.LeaderController().GetType().Name)){<text>class="active"</text>}   }>@new {linktext = "leader", actionname="index", controllername="leader", roles="administrator, leader"}</li>
              <li @{if (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.ProviderController().GetType().Name)){<text>class="active"</text>}   }>@new {linktext = "grant provider", actionname="index", controllername="provider", roles="administrator, provider"}</li>
              <li @{if (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.EmployerController().GetType().Name)){<text>class="active"</text>}   }>@new {linktext = "employer", actionname="index", controllername="employer", roles="administrator, employer"}</li>
              <li @{if (ViewContext.Controller.GetType().Name.Equals(new NurseryS.Controllers.AdminController().GetType().Name)){<text>class="active"</text>}   }>@new {linktext = "admin", actionname="index", controllername="admin", roles="administrator"}</li>
                <li class="divider-vertical"></li>
                <li class="divider-vertical"></li>
                <li id="login">@Html.Partial("_loginpartial")</li>
            </ul>
          </div><!--/.nav-collapse -->
    </div>
}*@